# Generated by Django 3.0.5 on 2020-04-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200417_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='following',
        ),
    ]
